# The name of this app. Must be unique within a project.
name: "lnclassapp"

type: "ruby:3.0"

dependencies:
    nodejs:
        yarn: "*"

relationships:
    database: 'db:postgresql'

disk: 1024

variables:
    env:
        
        BUNDLE_DEPLOYMENT: '1'
        BUNDLE_ERROR_ON_STDERR: '1'
        BUNDLE_WITHOUT: 'development:test'
        DEFAULT_BUNDLER_VERSION: "2.3.25" # in case none is mentioned in Gemfile.lock
        EXECJS_RUNTIME: 'Node'
        NODE_ENV: 'production'
        NODE_VERSION: v14.17.6
        NVM_VERSION: v0.38.0
        RACK_ENV: 'production'
        RAILS_ENV: 'production'
        RAILS_LOG_TO_STDOUT: '1'
        RAILS_TMP: '/tmp'

hooks:
    build: |
        bundle install    
    deploy: |
        RACK_ENV=production bundle exec rake db:migrate:reset


mounts:
    "/log":
        source: local
        source_path: log
    "/storage":
        source: local
        source_path: storage
    "/tmp":
        source: local
        source_path: tmp

web:
    upstream:
        socket_family: unix
    commands:
        start: "bundle exec unicorn -l $SOCKET"
    locations:
        "/":
            root: "public"
            passthru: true
            expires: 1h
            allow: true